vich_uploader:
    db_driver: orm
    mappings:
        photos:
            uri_prefix: 'public/photos/'
            upload_destination: '%kernel.project_dir%/public/photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    metadata:
            type: attribute

    
        