vich_uploader:
    db_driver: orm

    metadata:
            type: attribute

    mappings:
        fromage_photos:
            uri_prefix: /photos/
            upload_destination: '%kernel.project_dir%/public/photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        